version: "3.8"
services:
  frps:
    image: fatedier/frps:v0.51.0
    container_name: frps
    hostname: frps
    user: nobody:nogroup
    restart: always
    command: -c /etc/frp/frps.ini
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /home/docker/frps/config:/etc/frp
    network_mode: host
volumes:
  data:
